# Generated by Django 5.2 on 2025-05-03 12:03

import web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inviteduser',
            name='expires_at',
            field=models.DateTimeField(default=web.models.InvitedUser.default_expires_at),
        ),
    ]
