# Generated by Django 5.2 on 2025-05-03 20:38

import django.db.models.deletion
import web.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_change_invited_user_expiry_logic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('git_url', models.URLField()),
                ('git_branch', models.CharField(default='main', max_length=255)),
                ('template', models.CharField(choices=[('none', 'None'), ('static', 'Static')], default='none', max_length=50)),
                ('port', models.IntegerField(default=web.models.Project.generate_safe_port)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
