services:
  svs:
    depends_on:
      - caddy
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: svs
    restart: "no"
    ports:
      - 8096:8096
    environment:
      - ALLOWED_HOSTS=localhost,127.0.0.1
    labels:
      - "caddy=svs.gyarab.cz" # Replace with env DOMAIN
      - "caddy.reverse_proxy={{upstreams 80}}"
    env_file:
      - ../.env
    volumes:
      - svs-data:/app/data

  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    container_name: caddy
    restart: "no"
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_shared:/data

volumes:
  svs-data:
  caddy_shared:
