services:
  adminer:
    image: ghcr.io/coleifer/sqlite-web:latest
    container_name: sqlite-web
    restart: "no"
    ports:
      - 8080:8080
    volumes:
      - ../data/db.sqlite3:/db/db.sqlite3
    command: sqlite_web --host 0.0.0.0 /db/db.sqlite3
