services:
  svs:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: svs
    restart: "no"
    ports:
      - 8096:8096
    environment:
      - ALLOWED_HOSTS=localhost,127.0.0.1
    env_file:
      - ../.env
    volumes:
      - svs-data:/app/data

  caddy:
    build:
      context: ../caddy
      dockerfile: Dockerfile
    container_name: caddy
    restart: "no"
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy_shared:/etc/caddy:ro
      - caddy_shared:/srv:ro
      - caddy_shared:/data:rw
      - caddy_shared:/config:rw

volumes:
  svs-data:
  caddy_shared:
