services:
    postgres:
        image: postgres:latest
        container_name: postgres
        env_file:
            - ../.env
        ports:
            - "${POSTGRES_PORT}:${POSTGRES_PORT}"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    adminer:
        image: adminer:latest
        container_name: adminer
        environment:            
            ADMINER_DEFAULT_SERVER: postgres
        ports:
            - "8080:8080"

volumes:
  postgres_data:
