FROM nginx:alpine

COPY . /usr/share/nginx/html
EXPOSE {{port}}

HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 \
    CMD wget --no-verbose --tries=1 --spider http://localhost:{{port}}/ || exit 1

CMD ["nginx", "-g", "daemon off;"]
